### ISSUE TITLE
Add transition effect when going from one step to another

### ISSUE THREAD

**Issue by smohadjer** [smohadjer/formwizard#13]
I suggest we implement a animated transition between the steps so it’s easier to see the difference between js and no-js versions. For example we can display all steps on one page as accordions which expand and collapse when user clicks on them. Of course accordions only expand if user is allowed to see an step (= has submitted all preceding steps). If there is no js, every time you click on an accordion the page will refresh, but if js is enabled accordion opens with an animation. If you don’t think such expandable/collapsable accordion is a good UI, we can use a slider UI. That is we only show one step in the viewport and when submit or back buttons are clicked, the current view slides out of view and then other view slides in. Preferably we should implement both UI as demos as each may have different challenges.

**Comment by amcoho** [comment]
Do a slider if it is not too much work. I am a bit wary of using expandable/collapsible approach because once you add substeps, it eat into screen real-estate (the width)

**Comment by smohadjer** [comment]
For a slider effect, we would need to know current step number. It can be inserted by backend as a data-attribute on form (data-step=2) or I can get it from url query with javascript. I think the latter is the better approach. What do you think?

**Comment by amcoho** [comment]
get it from url query

------ Original Message ------

**Comment by smohadjer** [comment]
I have added some basic sliding animation to submit and back buttons. For browser back/forward button there is a glitch that I have to fix yet, but at least now it's easy to recognise js and no-js version from one another.

**Comment by smohadjer** [comment]
I fixed the glitch with browser back/forward button, so no transition from one step to another is always animated regardless of how you do it.

**Comment by smohadjer** [comment]
@Saeid: Refactor sliding script so it's possible to jump more than one step as we would need that when we display a navigation above the page. Also sliding should work without use of absolute positioning. After slider is done, put sliding script and stylesheet in a separate repository so it can become basis for a new slider.

**Comment by smohadjer** [comment]
@amcoho I think we need to store step number of each step and total number of steps in data attributes on each form (data-step and data-total-steps).

**Comment by smohadjer** [comment]
@Saeid Fix glitch in slide effect when server returns us to current step due to an error.

**Comment by amcoho** [comment]
but you have the step # in the url, step # will never deviate from url. total number, yes, I can see you may want to use it. Again think about the implications with multi-steps as well. Ideally, we want step 1.5 (step 1, substep 5) to be indicated in URL as such.

**Comment by amcoho** [comment]
So you want a data-this-step and a data-all-steps?

How do we handle adding an item to a list repeatedly in terms of steps?

**Comment by smohadjer** [comment]
The data-step attribute should be set on the form element itself, as that indicates which step that form is. The data-steps on the other hand should be set on container div.formwizard as it gives us meta data about the structure of the component and we only need that when we initialize the component.

On 18. Jul 2018, at 07:39, amcoho <notifications@github.com> wrote:

So you want a data-this-step and a data-all-steps?

How do we handle adding an item to a list repeatedly in terms of steps?

**Comment by amcoho** [comment]
No, it is not clear to me how we implement an add to list pattern in 
terms of steps. How would the history behave and all other implications. 
Maybe we should bring this into the example to flush all complications.

------ Original Message ------

**Comment by smohadjer** [comment]
Yes, go ahead and add new steps before the last step for that. Once you get it working in no-js let me know and I will update js code, in case it needs to be updated at all.

**Comment by smohadjer** [comment]
Make sure you use a new branch for add-to-list example.

**Comment by smohadjer** [comment]
Also open a new issue for add-to-list. That is a separate task.

**Comment by smohadjer** [comment]
> No, it is not clear to me how we implement an add to list pattern in
terms of steps. How would the history behave and all other implications.
Maybe we should bring this into the example to flush all complications.

As far as I can see anything we do inside a single step (or a single sub-step) is out-of-scope of this boilerplate. Things we do inside a step should have no impact on how the component works and should not require changes to formwizard script. To make sure this is indeed the case add a new step where user can add some names to a list.

**Comment by smohadjer** [comment]
@amcoho We don't need a data-step on form elements anymore. That would have made adding steps difficult since one had to update value of this attribute on all other steps every time a new step was being added. I get the step from request.responseURL instead. But I added a data-steps-count to component itself (not to steps).

**Comment by smohadjer** [comment]
By the way now it's possible to slide to any step. To show this I added a back link to step 3 that takes you to step 1.

**Comment by amcoho** [comment]
I don't see the data-steps attribute we discussed e.g. data-steps="1 1.1 1.2 2 2.1 2.2 2.3 3"

**Comment by smohadjer** [comment]
I’m done with this task. Can you review so we can close it?
