### ISSUE TITLE
Add List/Add Item Example

### ISSUE THREAD

**Issue by amcoho** [smohadjer/formwizard#20]

**Comment by smohadjer** [comment]
Item quantity is showing wrong in the table. Please fix.

**Comment by smohadjer** [comment]
When we are in step 3 sub-step 2 and click next we are taken to sub-step 1 of step 3, but url still shows mode=add in address bar, which it shouldn't. This problem only happens in js version, so the code that updates address bar should be refactored to avoid this problem.

**Comment by smohadjer** [comment]
Fixed here: https://github.com/smohadjer/formwizard/commit/8833b5400a4e0c13a6ef0f79ccfebe774cb950bc
