### ISSUE TITLE
Handling server-side validation errors on frontend

### ISSUE THREAD

**Issue by smohadjer** [smohadjer/formwizard#3]
If some form fields show error messages inserted by server, javascript should remove these errors as soon as the user corrects them, possibly by calling a server-side validator endpoint using ajax to figure out if the new value is valid or not.

**Comment by amcoho** [comment]
Let's not do this. The nature of a field can be such that it cannot be validated by itself e.g. British Columbia is a valid value for state field if the value of country field is Canada but not if it is United States.
